name: "CI"
on: push

jobs:
  create_release:
    name: Create release
    if: contains(github.ref, 'tags')
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        config:
          - { os: macos-latest, arch: x86_64, python-arch: x64, name: darwin }
          - { os: ubuntu-latest, arch: x86_64, python-arch: x64, name: linux }
          - { os: windows-latest, arch: x86_64, python-arch: x64, name: windows }
    steps: 
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.0'
        id: go
      - name: Install dependencies
        run: |
          go version
          go mod download
          go get -u golang.org/x/lint/golint
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      # - name: Run testing
      #   run: cd test && go test -v
      - name: Run build
        run: go build  -o out/kubectl-deploy-${{ matrix.config.arch }}-${{ matrix.config.name }} .
      - name: Upload binaries to the new release
        if: contains(github.ref, 'tags')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/kubectl-deploy*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      # - name: Send slack notification
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: always()

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }} 
  #   steps:
  #     - name: Checkout 🛎️
  #       uses: actions/checkout@v2.3.1
  #     - name: Deploy to Docker registry
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #         repository: ${{ secrets.DOCKER_HUB }}/kubedeploy
  #         tag_with_ref: true
